// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBro0c0M7WWwna3E0Dq7J-4ZI2iNv0OGgw',
    appId: '1:547402194935:web:826d716fe07d97ca8458f2',
    messagingSenderId: '547402194935',
    projectId: 'finalspotify220103',
    authDomain: 'finalspotify220103.firebaseapp.com',
    storageBucket: 'finalspotify220103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXOzRSoa6xJjzfWUOogBQ2UL6fuFr4fuA',
    appId: '1:547402194935:android:a6195816cb49550a8458f2',
    messagingSenderId: '547402194935',
    projectId: 'finalspotify220103',
    storageBucket: 'finalspotify220103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8ZmUqkELWnYDs81KQGym-T_UNOZO7A8',
    appId: '1:547402194935:ios:955ddb3b7447242c8458f2',
    messagingSenderId: '547402194935',
    projectId: 'finalspotify220103',
    storageBucket: 'finalspotify220103.appspot.com',
    iosBundleId: 'com.example.spotifyfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8ZmUqkELWnYDs81KQGym-T_UNOZO7A8',
    appId: '1:547402194935:ios:955ddb3b7447242c8458f2',
    messagingSenderId: '547402194935',
    projectId: 'finalspotify220103',
    storageBucket: 'finalspotify220103.appspot.com',
    iosBundleId: 'com.example.spotifyfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBro0c0M7WWwna3E0Dq7J-4ZI2iNv0OGgw',
    appId: '1:547402194935:web:9f1d0a62bd7ae5138458f2',
    messagingSenderId: '547402194935',
    projectId: 'finalspotify220103',
    authDomain: 'finalspotify220103.firebaseapp.com',
    storageBucket: 'finalspotify220103.appspot.com',
  );
}
